const fs=require('fs');
const obj={
  openapi:'3.0.3',
  info:{ title:'F-Grade Corporate AI Backend', description:'Unified backend API for F-Grade Corporate AI, including the new intelligent Zoho CRM endpoint.', version:'1.0.0', contact:{name:'F-Grade'}, license:{name:'Internal Use Only'} },
  servers:[{url:'https://unweighted-elois-trinomially.ngrok-free.dev', description:'Public API'}],
  tags:[{name:'System',description:'System endpoints'},{name:'CRM',description:'Zoho CRM endpoints'}],
  paths: {
    '/health': { get: { tags:['System'], summary:'Health Check', description:'Returns the backend health status.', operationId:'getHealth', parameters:[], responses:{ '200':{ description:'Request succeeded.', content:{ 'application/json':{ schema:{ $ref:'#/components/schemas/HealthResponse' } } } } } } },
    '/api/crm': { get: { tags:['CRM'], summary:'Query Zoho CRM modules', description:'Retrieve records from a Zoho CRM module using a single intelligent endpoint. Specify the module name and optional parameters.', operationId:'getCrmRecords', parameters:[ { name:'module', in:'query', description:'Zoho CRM module to query.', required:true, schema:{ type:'string', enum:['leads','contacts','accounts','deals','tasks','events','calls','meetings','notes','products','vendors','quotes','sales-orders','purchase-orders','campaigns','cases','solutions','users','organization','partners','enterprise-leads','renewal-accounts','service-provider','co-operative-banks','documents'] } }, { name:'page', in:'query', description:'Page number for pagination.', schema:{ type:'integer', minimum:1, example:1 } }, { name:'per_page', in:'query', description:'Number of records per page.', schema:{ type:'integer', minimum:1, example:25 } }, { name:'ids', in:'query', description:'Comma-separated Zoho record IDs.', schema:{ type:'string', example:'1234567000000123456,1234567000000123457' } }, { name:'fields', in:'query', description:'Comma-separated list of Zoho field names to return.', schema:{ type:'string', example:'Name,Email,Phone' } }, { name:'filters', in:'query', description:'Zoho CRM criteria expression to filter results.', schema:{ type:'string', example:'(Lead_Source:equals:Webinar)' } } ], responses:{ '200':{ description:'Successful CRM response.', content:{ 'application/json':{ schema:{ $ref:'#/components/schemas/CRMResponse' } } } }, '400':{ description:'Bad request due to invalid parameters.', content:{ 'application/json':{ schema:{ $ref:'#/components/schemas/CRMErrorResponse' } } } }, '500':{ description:'Internal server error or Zoho API failure.', content:{ 'application/json':{ schema:{ $ref:'#/components/schemas/CRMErrorResponse' } } } } } } }
  },
  components:{
    schemas:{
      HealthResponse:{ type:'object', properties:{ status:{type:'string', example:'OK'}, service:{type:'string', example:'F-Grade Corporate AI Backend'} } },
      CRMQueryRequest:{ type:'object', required:['module'], properties:{ module:{ type:'string', description:'Zoho CRM module to query.', enum:['leads','contacts','accounts','deals','tasks','events','calls','meetings','notes','products','vendors','quotes','sales-orders','purchase-orders','campaigns','cases','solutions','users','organization','partners','enterprise-leads','renewal-accounts','service-provider','co-operative-banks','documents'] }, page:{ type:'integer', minimum:1, description:'Page number to retrieve.' }, per_page:{ type:'integer', minimum:1, description:'Number of records to return per page.' }, ids:{ oneOf:[ {type:'string', description:'Comma-separated list of IDs.'},{type:'array', items:{type:'string'}, description:'Array of IDs.'} ] }, fields:{ oneOf:[ {type:'string', description:'Comma-separated field names.'},{type:'array', items:{type:'string'}, description:'Array of field names.'} ] }, filters:{ oneOf:[ {type:'string', description:'Zoho CRM criteria expression.'},{type:'object', description:'Structured filter object.'} ] } } },
      CRMResponse:{ type:'object', properties:{ success:{type:'boolean', example:true}, module:{type:'string', example:'Leads'}, count:{type:'integer', example:18}, page:{type:'integer', example:1}, per_page:{type:'integer', example:25}, executionTime:{type:'string', example:'52.67ms'}, source:{type:'string', example:'Zoho CRM'}, data:{ type:'array', items:{ type:'object', additionalProperties:true } } }, required:['success','module','data'] },
      CRMErrorResponse:{ type:'object', properties:{ success:{type:'boolean', example:false}, module:{type:'string', example:'unknown'}, status:{type:'integer', example:400}, error:{type:'string', example:'Unsupported CRM module: projects'}, invalidFields:{ type:'array', items:{type:'string'}, example:['Contact_Name'] } } }
    }
  }
};
fs.writeFileSync('./openapi.json', JSON.stringify(obj, null, 2), 'utf8');
console.log('WROTE_OPENAPI');
